### ISSUE TITLE
BOR diff

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/csl-devanagari#10]
```
87221c87221
< <L>15397<pc>471<k1>news-vender <k2>news-vender
---
> <L>15397<pc>471<k1>news-vender <k2>news-vender 
```

**Comment by drdhaval2785** [comment]
https://github.com/sanskrit-lexicon/CORRECTIONS/issues/92#issuecomment-913174476
```
	Line 63386:	<div n="lb"/>{@HOBSON'S CHOICE:@}¦ {#॥॥॥भृत्याभिरुचिः#} (??).
		%% Borooah himself had it marked thus.
		%% This clearly indicates the need for "taking out" all punctuations out of Devanagari strings. Here it is ellipsis that should be present.
```

**Comment by Andhrabharati** [comment]
Otherwise, the content like-

![2](https://user-images.githubusercontent.com/75209130/132172929-dd22195a-5025-4e68-b800-5c31279bc766.png)

becomes this way-

![1](https://user-images.githubusercontent.com/75209130/132172980-4507eb7a-f30a-4a48-bcca-6a1d0f171483.png)


It is easy to correct such cases of occassional citations like this (in majority texts), but is hell of a work with works abounding with citations like PWG and AP90 (esp. they being bi-lingual ones with both '.' and '। or॥' valid at resp. places). In fact I tried doing in PWG, but left it after spending sometime on this point, as it was too much time-taking to go through the content for proper changes only at the necessary place.

**can @funderburkjim come up with some idea to make this change easier?**

`------------`
Speaking of AP90 reminds me of its losing its "date" (1890 to 1920) on the CDSL home page, **and falling down in the chronological order**. Do not know when it gets back the correct date!!

**Comment by funderburkjim** [comment]
Search for three periods  within Sanskrit text for the ellipsis problem.

For example: 
```
77 matches for "{#[^#]*[.][.][.]" in buffer: bor.txt
```

**Comment by funderburkjim** [comment]
Regarding AP90 homepage, https://github.com/sanskrit-lexicon/csl-homepage/issues/6

**Comment by Andhrabharati** [comment]
@funderburkjim 

pl. look at this-
https://github.com/sanskrit-lexicon/ApteES/issues/6#issuecomment-907241453

**Comment by funderburkjim** [comment]
I think this issue can be  closed but will let @drdhaval2785 decide since he opened.
