### ISSUE TITLE
Not all metalines to be with Devanagari text!!

### ISSUE THREAD

**Issue by Andhrabharati** [sanskrit-lexicon/csl-devanagari#25]
Here is the list, as per the print version-

cat.1 : LAN
cat.2 : AE, BOR, MWE
cat.3 : BUR (other than major ones), STC
cat.4 : GRA
cat.7 : INM, VEI, PUI, BHS, IEG, SNP, PGN, MCI

**Atleast the 4 works AE, BOR, MWE, IEG should not be.**
`-----------`
MW can be ignored in this list, as it is bring worked upon for over 20 years now.
(However the HW proofing is still required as pointed out few months back.)

**Comment by drdhaval2785** [comment]
I do not know what is required in this issue.

**Comment by drdhaval2785** [comment]
AE, BOR, MWE and IEG - headwords not converted to Devanagari.

**Comment by drdhaval2785** [comment]
What is to be done with cat 1,2,3,4 and 7?

**Comment by funderburkjim** [comment]
In the display programs,  AE, BOR, and MWE are treated specially as 'English' -- this is used to avoid conversion of
headwords (such as to devanagari)

However, headwords in IEG ARE treated as Sanskrit.   

I can't tell if there is an unresolved problem,  although since issue is Closed,  won't worry further.
